import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import JSZip from 'jszip';

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ projectId: string }> }
) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const userId = user.id;
  const { projectId } = await params;

  try {
    const { data: project } = await supabase
      .from('projects')
      .select('*')
      .eq('id', projectId)
      .eq('user_id', userId)
      .single();

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const { data: files } = await supabase
      .from('project_files')
      .select('*')
      .eq('project_id', projectId);

    const projectFiles = files ?? [];

    const zip = new JSZip();

    // Add all project files
    for (const file of projectFiles) {
      zip.file(file.path, file.content);
    }

    // Generate package.json if not present
    const hasPackageJson = projectFiles.some((f) => f.path === 'package.json');
    if (!hasPackageJson) {
      const packageJson = {
        name: project.name.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
        version: '1.0.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          next: '^15.0.0',
        },
        devDependencies: {
          typescript: '^5.0.0',
          '@types/react': '^19.0.0',
          '@types/node': '^22.0.0',
          tailwindcss: '^4.0.0',
        },
      };
      zip.file('package.json', JSON.stringify(packageJson, null, 2));
    }

    // Generate README.md if not present
    const hasReadme = projectFiles.some(
      (f) => f.path.toLowerCase() === 'readme.md'
    );
    if (!hasReadme) {
      const fileList = projectFiles
        .map((f) => '- `' + f.path + '`')
        .join('\n');

      const readme = '# ' + project.name + '\n\n' +
        (project.description || 'A project built with CodeWIX Builder.') + '\n\n' +
        '## Getting Started\n\n' +
        'To run the project:\n\n' +
        '```bash\nnpm install\nnpm run dev\n```\n\n' +
        'Open [http://localhost:3000](http://localhost:3000) in your browser.\n\n' +
        '> Built with [CodeWIX](https://codewix.in) Builder.\n\n' +
        '## Project Structure\n\n' +
        fileList + '\n\n' +
        '---\n*Generated by CodeWIX Builder*\n';

      zip.file('README.md', readme);
    }

    // Generate the zip buffer
    const buffer = await zip.generateAsync({ type: 'uint8array' });

    // Return as downloadable file
    const safeName = project.name.replace(/[^a-z0-9-]/gi, '-');
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': 'attachment; filename="' + safeName + '.zip"',
      },
    });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Failed to export project' }, { status: 500 });
  }
}
