import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getAuthUserId } from '@/lib/auth-helper';
import JSZip from 'jszip';

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ projectId: string }> }
) {
  const userId = await getAuthUserId();
  if (userId instanceof NextResponse) return userId;

  const { projectId } = await params;

  try {
    const project = await db.project.findFirst({
      where: { id: projectId, userId },
      include: { files: true },
    });

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const zip = new JSZip();

    // Add all project files
    for (const file of project.files) {
      zip.file(file.path, file.content);
    }

    // Generate package.json if not present
    const hasPackageJson = project.files.some((f) => f.path === 'package.json');
    if (!hasPackageJson) {
      const packageJson = {
        name: project.name.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
        version: '1.0.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          next: '^15.0.0',
        },
        devDependencies: {
          typescript: '^5.0.0',
          '@types/react': '^19.0.0',
          '@types/node': '^22.0.0',
          tailwindcss: '^4.0.0',
        },
      };
      zip.file('package.json', JSON.stringify(packageJson, null, 2));
    }

    // Generate README.md if not present
    const hasReadme = project.files.some(
      (f) => f.path.toLowerCase() === 'readme.md'
    );
    if (!hasReadme) {
      const fileList = project.files
        .map((f) => '- `' + f.path + '`')
        .join('\n');

      const readme = '# ' + project.name + '\n\n' +
        (project.description || 'A project built with CodeWIX Builder.') + '\n\n' +
        '## Getting Started\n\n' +
        'To run the project:\n\n' +
        '```bash\nnpm install\nnpm run dev\n```\n\n' +
        'Open [http://localhost:3000](http://localhost:3000)\n\n' +
        '## Project Structure\n\n' +
        fileList + '\n\n' +
        '---\n*Generated by CodeWIX Builder*\n';

      zip.file('README.md', readme);
    }

    // Generate the zip buffer
    const buffer = await zip.generateAsync({ type: 'uint8array' });

    // Return as downloadable file
    const safeName = project.name.replace(/[^a-z0-9-]/gi, '-');
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': 'attachment; filename="' + safeName + '.zip"',
      },
    });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Failed to export project' }, { status: 500 });
  }
}
